name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    environment: stage
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Get changed files
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: powerbi-samples/reports/**.pbix

      - name: List all added files
        env:
          ALL_ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
        run: |
          for file in ${ALL_ADDED_FILES}; do
            echo "$file was added"
          done
          
      - name: List all modified files
        env:
          ALL_MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
        run: |
          for file in ${ALL_MODIFIED_FILES}; do
            echo "$file was modified"
          done

      - name: Deploy New Power BI Reports
        if: ${{ steps.changed-files.outputs.added_files }}
        run: |
          echo "Deploying new Power BI reports to stage environment"
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "Deploying $file"
          done